---

- hosts: all
  become: true
  pre_tasks:

  - name: Ubuntu Update
    tags: always
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: Ubuntu
  become: true
  roles:
    - role: keystone
    - role: glance
    - role: nova
